name: resume_builder_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  dio: ^5.8.0+1
  flutter_bloc: ^9.0.0
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.1
  firebase_database: ^11.3.3
  cloud_firestore: ^5.6.4
  google_sign_in: ^6.2.2
  flutter_launcher_icons: ^0.14.3
  get_it: ^8.0.3
  shared_preferences: ^2.5.2
  firebase_storage: ^12.4.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.15
  bloc_test: ^10.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "assets/icons/background.png"
  adaptive_icon_foreground: "assets/icons/foreground.png"
